packages:
  - presentations/*
  - packages/*

allowBuilds:
  esbuild: true
  playwright-chromium: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@slango.configs/*'

onlyBuiltDependencies:
  - esbuild
